[theme]
base                     = "dark"
primaryColor             = "#818cf8"
backgroundColor          = "#18181b"
secondaryBackgroundColor = "#27272a"
textColor                = "#fafafa"
font                     = "sans serif"
